name: Deploy TRC HTML

on:
  push:
    branches:
      - main  # Adjust this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Replace secrets in HTML
      run: |
        sed -i 's|__CLIENT_ID__|${{ secrets.CLIENT_ID }}|g' create-trc.html
        sed -i 's|__CLIENT_SECRET__|${{ secrets.CLIENT_SECRET }}|g' create-trc.html
        sed -i 's|__REFRESH_TOKEN__|${{ secrets.REFRESH_TOKEN }}|g' create-trc.html

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add create-trc.html
        git commit -m 'Update create-trc.html with secrets'
        git push origin main